# Generated by Django 6.0.2 on 2026-02-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_olist', models.CharField(blank=True, help_text='ID do produto no ERP Olist', max_length=50, null=True, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('comprimento_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('largura_cm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='products.categoria')),
            ],
        ),
    ]
