# Generated by Django 6.0.2 on 2026-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='EAN / GTIN do produto', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Upload direto do painel (Prioridade máxima)', null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='URL de fallback da API', max_length=500, null=True),
        ),
    ]
