# Generated by Django 6.0.2 on 2026-02-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produto_codigo_barras_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='EAN / GTIN do produto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_olist',
            field=models.CharField(blank=True, help_text='ID do produto no ERP Olist', max_length=255, null=True, unique=True),
        ),
    ]
